name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd scripts && npm install
      - run: cd scripts && npx node --loader @k-foss/ts-esnode --experimental-specifier-resolution=node ./src/index.ts ${{github.token}}
